name: Android PR check
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-action:
    if: github.event_name == 'pull_request' || contains(github.event.comment.body, '/rebase') || contains(github.event.comment.body, '/autosquash')
    timeout-minutes: 100
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event_name }}"
